baseURL = "http://acornapps.github.io/cengjiyun-manual-3.2.1-public"
languageCode = "kr-ko"
title = "칵테일 클라우드"
theme = "hugo-theme-learn"
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir= true


[author]
    name = "cloud.jung"
    email = "cloud.jung@acornsoft.io"

[params]
    imageRootDir = "/cengjiyun-manual-3.2.1-public/images"
    version = "3.2.1"
    # Disable search function. It will hide search bar
    disableSearch = true
    # Hide breadcrumbs in the header and only show the current page title
    disableBreadcrumb = false
    # Order sections in menu by "weight" or "title". Default to "weight"
    ordersectionsby = "weight"

    themeVariant = "cocktail"
#    themeVariant = "green"

[outputs]
home = [ "HTML", "RSS", "JSON"]


[Languages]
[Languages.ko]
title = "칵테일 클라우드 메뉴얼"
weight = 1
languageName = "Korean"
contentDir = "content/ko"

[Languages.en]
title = "Cocktail Cloud Manual"
weight = 2
languageName = "English"
contentDir = "content/en"

[Languages.zh]
title = "Cengjiyun Manual"
weight = 3
languageName = "Chinese"
contentDir = "content/zh"